# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\deftui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWinDefectInfo(object):
    def setupUi(self, mainWinDefectInfo):
        mainWinDefectInfo.setObjectName("mainWinDefectInfo")
        mainWinDefectInfo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWinDefectInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnBrowseDefectDb = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseDefectDb.setObjectName("btnBrowseDefectDb")
        self.gridLayout.addWidget(self.btnBrowseDefectDb, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtDefectFileLoc = QtWidgets.QLineEdit(self.groupBox)
        self.txtDefectFileLoc.setObjectName("txtDefectFileLoc")
        self.gridLayout.addWidget(self.txtDefectFileLoc, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtImageRootDir = QtWidgets.QLineEdit(self.groupBox)
        self.txtImageRootDir.setObjectName("txtImageRootDir")
        self.gridLayout.addWidget(self.txtImageRootDir, 1, 1, 1, 1)
        self.btnBrowseImgRoot = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseImgRoot.setObjectName("btnBrowseImgRoot")
        self.gridLayout.addWidget(self.btnBrowseImgRoot, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.listDirs = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listDirs.sizePolicy().hasHeightForWidth())
        self.listDirs.setSizePolicy(sizePolicy)
        self.listDirs.setObjectName("listDirs")
        self.horizontalLayout.addWidget(self.listDirs)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.listImages = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listImages.sizePolicy().hasHeightForWidth())
        self.listImages.setSizePolicy(sizePolicy)
        self.listImages.setObjectName("listImages")
        self.horizontalLayout_2.addWidget(self.listImages)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.txtStats = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtStats.setObjectName("txtStats")
        self.verticalLayout_5.addWidget(self.txtStats)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutPreview = QtWidgets.QVBoxLayout()
        self.layoutPreview.setObjectName("layoutPreview")
        self.verticalLayout_2.addLayout(self.layoutPreview)
        self.verticalLayout.addWidget(self.groupBox_3)
        mainWinDefectInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWinDefectInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWinDefectInfo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWinDefectInfo)
        self.statusbar.setObjectName("statusbar")
        mainWinDefectInfo.setStatusBar(self.statusbar)

        self.retranslateUi(mainWinDefectInfo)
        QtCore.QMetaObject.connectSlotsByName(mainWinDefectInfo)

    def retranslateUi(self, mainWinDefectInfo):
        _translate = QtCore.QCoreApplication.translate
        mainWinDefectInfo.setWindowTitle(_translate("mainWinDefectInfo", "MainWindow"))
        self.groupBox.setTitle(_translate("mainWinDefectInfo", "Path settings"))
        self.btnBrowseDefectDb.setText(_translate("mainWinDefectInfo", "Browse..."))
        self.label.setText(_translate("mainWinDefectInfo", "Defect DB:"))
        self.label_2.setText(_translate("mainWinDefectInfo", "Image root:"))
        self.btnBrowseImgRoot.setText(_translate("mainWinDefectInfo", "Browse..."))
        self.groupBox_2.setTitle(_translate("mainWinDefectInfo", "Tools"))
        self.label_3.setText(_translate("mainWinDefectInfo", "Directory"))
        self.label_4.setText(_translate("mainWinDefectInfo", "Image"))
        self.groupBox_3.setTitle(_translate("mainWinDefectInfo", "Preview"))

