# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\deftui_imgpreview.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmImagePreview(object):
    def setupUi(self, frmImagePreview):
        frmImagePreview.setObjectName("frmImagePreview")
        frmImagePreview.resize(800, 429)
        self.centralwidget = QtWidgets.QWidget(frmImagePreview)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.layoutFigLeft = QtWidgets.QVBoxLayout()
        self.layoutFigLeft.setObjectName("layoutFigLeft")
        self.gridLayout.addLayout(self.layoutFigLeft, 0, 1, 1, 1)
        self.layoutFigRight = QtWidgets.QVBoxLayout()
        self.layoutFigRight.setObjectName("layoutFigRight")
        self.gridLayout.addLayout(self.layoutFigRight, 0, 2, 1, 1)
        self.btnPrevImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevImage.setObjectName("btnPrevImage")
        self.gridLayout.addWidget(self.btnPrevImage, 1, 1, 1, 1)
        self.btnNextImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextImage.setObjectName("btnNextImage")
        self.gridLayout.addWidget(self.btnNextImage, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        frmImagePreview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmImagePreview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSegments = QtWidgets.QMenu(self.menubar)
        self.menuSegments.setObjectName("menuSegments")
        self.menuAdaptive_threshold_2 = QtWidgets.QMenu(self.menuSegments)
        self.menuAdaptive_threshold_2.setObjectName("menuAdaptive_threshold_2")
        frmImagePreview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmImagePreview)
        self.statusbar.setObjectName("statusbar")
        frmImagePreview.setStatusBar(self.statusbar)
        self.actionApply_Canny = QtWidgets.QAction(frmImagePreview)
        self.actionApply_Canny.setCheckable(True)
        self.actionApply_Canny.setChecked(False)
        self.actionApply_Canny.setObjectName("actionApply_Canny")
        self.actionThreshold = QtWidgets.QAction(frmImagePreview)
        self.actionThreshold.setCheckable(True)
        self.actionThreshold.setChecked(False)
        self.actionThreshold.setObjectName("actionThreshold")
        self.actionApply_morph_opening_after = QtWidgets.QAction(frmImagePreview)
        self.actionApply_morph_opening_after.setCheckable(False)
        self.actionApply_morph_opening_after.setChecked(False)
        self.actionApply_morph_opening_after.setObjectName("actionApply_morph_opening_after")
        self.actionAdaptive_threshold_3 = QtWidgets.QAction(frmImagePreview)
        self.actionAdaptive_threshold_3.setCheckable(True)
        self.actionAdaptive_threshold_3.setChecked(True)
        self.actionAdaptive_threshold_3.setObjectName("actionAdaptive_threshold_3")
        self.action2_Morphological_opening = QtWidgets.QAction(frmImagePreview)
        self.action2_Morphological_opening.setCheckable(True)
        self.action2_Morphological_opening.setChecked(True)
        self.action2_Morphological_opening.setObjectName("action2_Morphological_opening")
        self.action0_Gaussian_blur = QtWidgets.QAction(frmImagePreview)
        self.action0_Gaussian_blur.setCheckable(True)
        self.action0_Gaussian_blur.setChecked(True)
        self.action0_Gaussian_blur.setObjectName("action0_Gaussian_blur")
        self.actionBlob_detector = QtWidgets.QAction(frmImagePreview)
        self.actionBlob_detector.setCheckable(True)
        self.actionBlob_detector.setChecked(True)
        self.actionBlob_detector.setObjectName("actionBlob_detector")
        self.menuAdaptive_threshold_2.addAction(self.action0_Gaussian_blur)
        self.menuAdaptive_threshold_2.addAction(self.actionAdaptive_threshold_3)
        self.menuAdaptive_threshold_2.addAction(self.action2_Morphological_opening)
        self.menuSegments.addAction(self.actionApply_Canny)
        self.menuSegments.addAction(self.actionThreshold)
        self.menuSegments.addAction(self.menuAdaptive_threshold_2.menuAction())
        self.menuSegments.addAction(self.actionBlob_detector)
        self.menubar.addAction(self.menuSegments.menuAction())

        self.retranslateUi(frmImagePreview)
        QtCore.QMetaObject.connectSlotsByName(frmImagePreview)

    def retranslateUi(self, frmImagePreview):
        _translate = QtCore.QCoreApplication.translate
        frmImagePreview.setWindowTitle(_translate("frmImagePreview", "MainWindow"))
        self.btnPrevImage.setText(_translate("frmImagePreview", "Previous image"))
        self.btnNextImage.setText(_translate("frmImagePreview", "Next image"))
        self.menuSegments.setTitle(_translate("frmImagePreview", "Preprocess"))
        self.menuAdaptive_threshold_2.setTitle(_translate("frmImagePreview", "Adaptive threshold"))
        self.actionApply_Canny.setText(_translate("frmImagePreview", "Canny edge detector"))
        self.actionThreshold.setText(_translate("frmImagePreview", "Threshold"))
        self.actionApply_morph_opening_after.setText(_translate("frmImagePreview", "Apply morph opening after"))
        self.actionAdaptive_threshold_3.setText(_translate("frmImagePreview", "1: Adaptive threshold"))
        self.action2_Morphological_opening.setText(_translate("frmImagePreview", "2: Morphological opening"))
        self.action0_Gaussian_blur.setText(_translate("frmImagePreview", "0: Gaussian blur"))
        self.actionBlob_detector.setText(_translate("frmImagePreview", "Blob detector"))

