# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\deftui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWinDefectInfo(object):
    def setupUi(self, mainWinDefectInfo):
        mainWinDefectInfo.setObjectName("mainWinDefectInfo")
        mainWinDefectInfo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWinDefectInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnBrowseDefectDb = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseDefectDb.setObjectName("btnBrowseDefectDb")
        self.gridLayout.addWidget(self.btnBrowseDefectDb, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtDefectFileLoc = QtWidgets.QLineEdit(self.groupBox)
        self.txtDefectFileLoc.setObjectName("txtDefectFileLoc")
        self.gridLayout.addWidget(self.txtDefectFileLoc, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtImageRootDir = QtWidgets.QLineEdit(self.groupBox)
        self.txtImageRootDir.setObjectName("txtImageRootDir")
        self.gridLayout.addWidget(self.txtImageRootDir, 1, 1, 1, 1)
        self.btnBrowseImgRoot = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseImgRoot.setObjectName("btnBrowseImgRoot")
        self.gridLayout.addWidget(self.btnBrowseImgRoot, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.listFilterDirs = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFilterDirs.sizePolicy().hasHeightForWidth())
        self.listFilterDirs.setSizePolicy(sizePolicy)
        self.listFilterDirs.setObjectName("listFilterDirs")
        self.horizontalLayout.addWidget(self.listFilterDirs)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.listFilterDefects = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFilterDefects.sizePolicy().hasHeightForWidth())
        self.listFilterDefects.setSizePolicy(sizePolicy)
        self.listFilterDefects.setObjectName("listFilterDefects")
        self.horizontalLayout_3.addWidget(self.listFilterDefects)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.chkShowOnlyWithSelectedDefect = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkShowOnlyWithSelectedDefect.setObjectName("chkShowOnlyWithSelectedDefect")
        self.horizontalLayout_4.addWidget(self.chkShowOnlyWithSelectedDefect)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.listImages = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listImages.sizePolicy().hasHeightForWidth())
        self.listImages.setSizePolicy(sizePolicy)
        self.listImages.setObjectName("listImages")
        self.horizontalLayout_2.addWidget(self.listImages)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.txtStats = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtStats.setObjectName("txtStats")
        self.verticalLayout_5.addWidget(self.txtStats)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        mainWinDefectInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWinDefectInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWinDefectInfo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWinDefectInfo)
        self.statusbar.setObjectName("statusbar")
        mainWinDefectInfo.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(mainWinDefectInfo)
        self.actionFile.setObjectName("actionFile")
        self.actionReload_image = QtWidgets.QAction(mainWinDefectInfo)
        self.actionReload_image.setObjectName("actionReload_image")
        self.actionPreview_window = QtWidgets.QAction(mainWinDefectInfo)
        self.actionPreview_window.setCheckable(True)
        self.actionPreview_window.setChecked(True)
        self.actionPreview_window.setObjectName("actionPreview_window")
        self.actionAnalysis_window = QtWidgets.QAction(mainWinDefectInfo)
        self.actionAnalysis_window.setCheckable(True)
        self.actionAnalysis_window.setChecked(True)
        self.actionAnalysis_window.setObjectName("actionAnalysis_window")
        self.actionCreate_mask_from_shapes = QtWidgets.QAction(mainWinDefectInfo)
        self.actionCreate_mask_from_shapes.setObjectName("actionCreate_mask_from_shapes")
        self.actionCreateMaskFromDefShapes = QtWidgets.QAction(mainWinDefectInfo)
        self.actionCreateMaskFromDefShapes.setObjectName("actionCreateMaskFromDefShapes")
        self.menuEdit.addAction(self.actionCreateMaskFromDefShapes)
        self.menuView.addAction(self.actionPreview_window)
        self.menuView.addAction(self.actionAnalysis_window)
        self.menuView.addAction(self.actionReload_image)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(mainWinDefectInfo)
        QtCore.QMetaObject.connectSlotsByName(mainWinDefectInfo)

    def retranslateUi(self, mainWinDefectInfo):
        _translate = QtCore.QCoreApplication.translate
        mainWinDefectInfo.setWindowTitle(_translate("mainWinDefectInfo", "MainWindow"))
        self.groupBox.setTitle(_translate("mainWinDefectInfo", "Path settings"))
        self.btnBrowseDefectDb.setText(_translate("mainWinDefectInfo", "Browse..."))
        self.label.setText(_translate("mainWinDefectInfo", "Defect DB:"))
        self.label_2.setText(_translate("mainWinDefectInfo", "Image root:"))
        self.btnBrowseImgRoot.setText(_translate("mainWinDefectInfo", "Browse..."))
        self.groupBox_2.setTitle(_translate("mainWinDefectInfo", "Tools"))
        self.label_3.setText(_translate("mainWinDefectInfo", "Filter by folder"))
        self.label_5.setText(_translate("mainWinDefectInfo", "Filter by defect"))
        self.chkShowOnlyWithSelectedDefect.setText(_translate("mainWinDefectInfo", "Only show this defect on images"))
        self.label_4.setText(_translate("mainWinDefectInfo", "Image"))
        self.label_6.setText(_translate("mainWinDefectInfo", "Log"))
        self.menuEdit.setTitle(_translate("mainWinDefectInfo", "Edit"))
        self.menuView.setTitle(_translate("mainWinDefectInfo", "View"))
        self.menuFile.setTitle(_translate("mainWinDefectInfo", "File"))
        self.actionFile.setText(_translate("mainWinDefectInfo", "File"))
        self.actionReload_image.setText(_translate("mainWinDefectInfo", "Reload image"))
        self.actionPreview_window.setText(_translate("mainWinDefectInfo", "Preview window"))
        self.actionAnalysis_window.setText(_translate("mainWinDefectInfo", "Analysis window"))
        self.actionCreate_mask_from_shapes.setText(_translate("mainWinDefectInfo", "Create mask from shapes"))
        self.actionCreateMaskFromDefShapes.setText(_translate("mainWinDefectInfo", "Create mask from shapes"))

